"""Propiedad comprado

Revision ID: 0455fb71e471
Revises: b90cf2deedd4
Create Date: 2024-09-02 10:24:37.631753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0455fb71e471'
down_revision = 'b90cf2deedd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrito_activo', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'carrito', ['carrito_activo'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('carrito_activo')

    # ### end Alembic commands ###
