"""Propiedad comprado

Revision ID: b90cf2deedd4
Revises: 2d379eadfab1
Create Date: 2024-09-02 10:20:16.217580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90cf2deedd4'
down_revision = '2d379eadfab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.drop_column('comprado')

    # ### end Alembic commands ###
