"""Ruta de imagen, en los productos

Revision ID: f88a984abfd6
Revises: 0455fb71e471
Create Date: 2024-09-04 20:41:16.785914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f88a984abfd6'
down_revision = '0455fb71e471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=120), nullable=False))
        batch_op.alter_column('proveedor',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint('usuario_ibfk_1', type_='foreignkey')
        batch_op.drop_column('carrito_activo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrito_activo', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('usuario_ibfk_1', 'carrito', ['carrito_activo'], ['id'])

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('proveedor',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
